export const ENV = {
  appId: process.env.VITE_APP_ID ?? process.env.APP_SESSION_AUDIENCE ?? "personal-finance-manager",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  googleClientId: process.env.GOOGLE_CLIENT_ID ?? "",
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET ?? "",
  googleRedirectUri: process.env.GOOGLE_REDIRECT_URI ?? "",
  localAuthUsername: process.env.LOCAL_AUTH_USERNAME ?? "",
  localAuthPassword: process.env.LOCAL_AUTH_PASSWORD ?? "",
  initialSetupToken: process.env.INITIAL_SETUP_TOKEN ?? "",
  allowedEmail: process.env.ALLOWED_EMAIL ?? "juanlu85@gmail.com",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
};
