import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { isoToday } from "@/lib/finance";
import { trpc } from "@/lib/trpc";
import { Loader2 } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

export type CategoryRecord = { id: number; name: string; direction: "income" | "expense"; color: string; icon: string | null; isActive: boolean };
export type ExchangeRateRecord = { id: number; fromCurrency: "EUR" | "USD"; toCurrency: "EUR" | "USD"; rate: string; effectiveOn: string; note: string | null };

export function CategoryDialog({ open, onOpenChange, category, defaultDirection }: { open: boolean; onOpenChange: (open: boolean) => void; category?: CategoryRecord | null; defaultDirection: "income" | "expense" }) {
  const utils = trpc.useUtils();
  const saveMutation = trpc.finance.categories.save.useMutation({ onSuccess: async () => { await utils.finance.categories.list.invalidate(); toast.success(category ? "Categoría actualizada" : "Categoría creada"); onOpenChange(false); }, onError: error => toast.error(error.message) });
  const [name, setName] = useState(""); const [direction, setDirection] = useState<"income" | "expense">(defaultDirection); const [color, setColor] = useState("#4C7A68"); const [isActive, setIsActive] = useState(true);
  useEffect(() => { if (!open) return; setName(category?.name ?? ""); setDirection(category?.direction ?? defaultDirection); setColor(category?.color ?? (defaultDirection === "income" ? "#4C7A68" : "#B76A4A")); setIsActive(category?.isActive ?? true); }, [open, category, defaultDirection]);
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!name.trim()) { toast.error("Indica un nombre para la categoría."); return; } saveMutation.mutate({ id: category?.id, name: name.trim(), direction, color, icon: null, isActive }); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle className="font-display text-2xl">{category ? "Editar categoría" : "Nueva categoría"}</DialogTitle><DialogDescription>Las categorías alimentan los gráficos y filtros de ingresos y gastos.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4 pt-2"><div className="space-y-2"><Label htmlFor="category-name">Nombre *</Label><Input id="category-name" autoFocus value={name} onChange={event => setName(event.target.value)} placeholder="Ej. Vivienda" /></div><div className="grid grid-cols-[1fr_auto] gap-3"><div className="space-y-2"><Label htmlFor="category-direction">Tipo</Label><select id="category-direction" value={direction} onChange={event => setDirection(event.target.value as "income" | "expense")} className="h-9 w-full rounded-md border border-input bg-transparent px-3 text-sm"><option value="income">Ingreso</option><option value="expense">Gasto</option></select></div><div className="space-y-2"><Label htmlFor="category-color">Color</Label><Input id="category-color" type="color" value={color} onChange={event => setColor(event.target.value)} className="h-9 w-14 p-1" /></div></div><label className="flex items-start gap-3 rounded-xl bg-secondary p-3 text-sm"><input type="checkbox" checked={isActive} onChange={event => setIsActive(event.target.checked)} className="mt-0.5 h-4 w-4 accent-primary" /><span><strong>Categoría activa</strong><span className="block text-muted-foreground mt-0.5">Las categorías inactivas se conservan para el histórico, pero no aparecen al registrar nuevos movimientos.</span></span></label><div className="flex justify-end gap-2 pt-2"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button><Button type="submit" disabled={saveMutation.isPending}>{saveMutation.isPending ? <><Loader2 className="h-4 w-4 mr-2 animate-spin" />Guardando</> : "Guardar"}</Button></div></form></DialogContent></Dialog>;
}

export function ExchangeRateDialog({ open, onOpenChange, rate }: { open: boolean; onOpenChange: (open: boolean) => void; rate?: ExchangeRateRecord | null }) {
  const utils = trpc.useUtils();
  const saveMutation = trpc.finance.exchangeRates.save.useMutation({ onSuccess: async () => { await Promise.all([utils.finance.exchangeRates.list.invalidate(), utils.finance.monthlySummary.invalidate(), utils.finance.monthlyTrend.invalidate()]); toast.success(rate ? "Tipo de cambio actualizado" : "Tipo de cambio guardado"); onOpenChange(false); }, onError: error => toast.error(error.message) });
  const [value, setValue] = useState(""); const [effectiveOn, setEffectiveOn] = useState(isoToday()); const [note, setNote] = useState("");
  useEffect(() => { if (!open) return; setValue(rate?.rate ?? ""); setEffectiveOn(rate?.effectiveOn ?? isoToday()); setNote(rate?.note ?? ""); }, [open, rate]);
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!Number(value) || Number(value) <= 0) { toast.error("Indica un tipo de cambio válido."); return; } saveMutation.mutate({ id: rate?.id, fromCurrency: "USD", rate: Number(value), effectiveOn, note: note.trim() || null }); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle className="font-display text-2xl">{rate ? "Editar tipo de cambio" : "Nuevo tipo de cambio"}</DialogTitle><DialogDescription>Registra cuántos EUR equivale a 1 USD. El valor se preserva para los informes históricos.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4 pt-2"><div className="space-y-2"><Label htmlFor="exchange-value">1 USD = EUR *</Label><Input id="exchange-value" autoFocus type="number" min="0.000001" step="0.000001" value={value} onChange={event => setValue(event.target.value)} placeholder="0,920000" /></div><div className="space-y-2"><Label htmlFor="exchange-date">Aplicable desde</Label><Input id="exchange-date" type="date" value={effectiveOn} onChange={event => setEffectiveOn(event.target.value)} /></div><div className="space-y-2"><Label htmlFor="exchange-note">Nota</Label><Input id="exchange-note" value={note} onChange={event => setNote(event.target.value)} placeholder="Ej. Cambio alquiler Ecuador" /></div><div className="flex justify-end gap-2 pt-2"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancelar</Button><Button type="submit" disabled={saveMutation.isPending}>{saveMutation.isPending ? <><Loader2 className="h-4 w-4 mr-2 animate-spin" />Guardando</> : "Guardar"}</Button></div></form></DialogContent></Dialog>;
}
